config/routes.rb
Rails.application.routes.draw do
  match '/people/form',    to: 'people#form', via: [:get, :post]
  post 'update_details', to: 'people#update_details'
  root 'people#form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  validate :phone_field_format
  validates :first_name, :last_name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, :presence => {:message => 'hello world, bad operation!'},
                    :numericality => true,
                    :length => { :minimum => 11, :maximum => 11 }

  def phone_field_format
  	errors.add(:phone, "number should start with +") unless self.phone.start_with?('+')
  end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	require 'csv'
  def form
  	if request.get?
  		@persons_array = JSON.parse(cookies[:all_persons]) unless cookies[:all_persons].nil?
  	end
  	if request.post?
  		cookies[:all_persons] = nil
  		@persons_array = []
  	  CSV.foreach(params[:file].path, headers: true) do |row|
        person = Person.create(first_name: row["First"], last_name: row["Last"], email: row["Email"], phone: row["Phone"])
        person_hash = {}
        person_hash["person_object"] = person
        person_hash["error_object"] = person.errors
        @persons_array << person_hash
      end
      cookies[:all_persons] = @persons_array.to_json
      redirect_to root_path
  	end
  end

  def update_details
  	person = Person.create(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], phone: params[:phone])
  	persons_object = JSON.parse(cookies[:all_persons])
  	persons_object[params[:index].to_i]["person_object"] = person
  	persons_object[params[:index].to_i]["error_object"] = person.errors
  	cookies[:all_persons] = persons_object.to_json
  	redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/form.html.erb
<div class="my-btn">
  <h4>Save Details</h4>
  <div class="two-btn">
    <%= form_tag people_form_path, id: 'person_data', :multipart => true do %>
      <div class="form-group">
        <span class="col-md-2 "><%=file_field_tag :file, class: 'form-control-file', required: true %></span>
        <span class="col-md-3"><%= submit_tag "Import CSV to Fill Form", id: 'submit_csv' %></span>
      </div>
    <%end%>
    <!-- <a href="#" class="btn-custom">First</a> -->
  </div>
</div>
<div class="box-body table-responsive" id="persons_table">
	<table class="table table-hover table-bordered" id="surfaces" >
    <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Errors </th>
      </tr>
    </thead>
    <tbody>
      <% @persons_array&.each_with_index do |item, index| %>
        <%if item["person_object"]["id"].nil? %>
          <%= form_tag update_details_path do %>
            <%= hidden_field_tag :index, index %>
            <tr>
              <td><%= item["person_object"]["id"] %></td>
              <td><%= text_field_tag :first_name, "", value: item["person_object"]["first_name"]%></td>
              <td><%= text_field_tag :last_name, "", value: item["person_object"]["last_name"]%></td>
              <td><%= text_field_tag :email, "", value: item["person_object"]["email"]%></td>
              <td class="phone_field"><%= text_field_tag :phone, "",value: item["person_object"]["phone"]%></td>
              <td>
                <% item["error_object"].each do |error, value| %>
                  <p><%= error + " " + value[0] %></p>
                <%end%>
              </td>
              <td>
                <%= submit_tag "Save"%>
              </td>
            </tr>
          <%end%>
        <%else%>
          <tr>
            <td><%= item["person_object"]["id"] %></td>
            <td><%= item["person_object"]["first_name"]%></td>
            <td><%= item["person_object"]["last_name"]%></td>
            <td><%= item["person_object"]["email"]%></td>
            <td><%= item["person_object"]["phone"]%></td>
            <td></td>
            <td> </td>
          </tr>
        <%end%> 
      <%end%>
    </tbody>
  </table>
</div>